pattern/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.PatternList.as_view(), name='patterns'),
    path('add_pattern/', views.add_pattern, name='add_pattern'),
    path('my_page/', views.my_page, name='my_page'),
    path('<slug:slug>/', views.pattern_details, name='pattern_details'),
    path('<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
    path('pattern/<slug:slug>/like/', views.like_pattern, name='like_pattern'),
    path('pattern/<slug:slug>/add-to-project/', views.add_to_project_list, name='add_to_project_list'),
]

theknitconnect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')


urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', index, name='index'),
    path('pattern/', include("pattern.urls")),
    path('user/', include("user.urls")),
]

user/urls.py
from django.urls import path
from . import views


urlpatterns = [ 
    path('', views.ProfilesList.as_view(), name='profiles'),
    path('add_profile/', views.add_profile, name='add_profile'),
    path('<str:username>/', views.user_profile, name='user_profile'),
]

pattern/models.py
from django.db import models
from user.models import User
from cloudinary.models import CloudinaryField
from django.utils.text import slugify


LEVEL = ((0, "Beginner"), (1, "Intermediate"), (2, "Advanced"))


class Pattern(models.Model):
    pattern_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(default="description")
    created_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE, related_name="patterncreator")
    featured_image = CloudinaryField('image')
    needle_size = models.CharField(max_length=100)
    gauge = models.CharField(max_length=100)
    yarn = models.CharField(max_length=100, default="yarn")
    difficulty_level = models.IntegerField(choices=LEVEL,)
    created_on = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(
        User,
        related_name='liked_patterns', blank=True)

    class Meta:
        ordering = ["created_on"]

    def save(self, *args, **kwargs):
        self.slug = slugify(self.pattern_name)
        super(Pattern, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.pattern_name} | by {self.created_by}"

    def like(self, user):
        if user not in self.likes.all():
            self.likes.add(user)

    def unlike(self, user):
        if user in self.likes.all():
            self.likes.remove(user)

    def like_count(self):
        return self.likes.count()


class Comment(models.Model):
    pattern = models.ForeignKey(
        Pattern, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="commenter")
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.author}"


class ProjectList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    patterns = models.ManyToManyField(Pattern, related_name='project_lists')
    

pattern/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Pattern, Comment


class PatternForm(forms.ModelForm):
    class Meta:
        model = Pattern
        fields = [
            'pattern_name',
            'description',
            'featured_image',
            'difficulty_level',
            'needle_size',
            'yarn',
            'gauge'
            ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

pattern/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.http import require_POST
from django.views import generic
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView, View
from django.http import HttpResponse, HttpResponseRedirect
from django.http import HttpResponseBadRequest
from django.forms import ModelForm
from django.utils.text import slugify
from django.http import JsonResponse
from .models import Pattern, Comment, ProjectList
from .forms import CommentForm, PatternForm
import cloudinary.uploader


class PatternList(generic.ListView):
    model = Pattern
    template_name = "pattern/patterns.html"
    paginate_by = 6


@login_required
def pattern_details(request, slug):
    pattern = get_object_or_404(Pattern, slug=slug)
    comments = Comment.objects.filter(pattern=pattern).order_by("-created_on")

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.pattern = pattern
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Comment submitted'
            )

    comment_form = CommentForm()

    # Count the number of likes for the pattern
    like_count = pattern.likes.count()

    return render(
        request,
        'pattern/pattern_details.html',
        {
            "pattern": pattern,
            "comments": comments,
            "comment_form": comment_form,
            "like_count": like_count,
        },
    )


@login_required
def comment_edit(request, slug, comment_id):

    if request.method == "POST":

        post = get_object_or_404(Pattern, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Error updating comment!')

    return HttpResponseRedirect(reverse('pattern_details', args=[slug]))


@login_required
def comment_delete(request, slug, comment_id):
    post = get_object_or_404(Pattern, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(request, messages.ERROR,
                             'You can only delete your own comments!')

    return HttpResponseRedirect(reverse('pattern_details', args=[slug]))


@login_required
def add_pattern(request):
    if request.method == "POST":
        pattern_form = PatternForm(request.POST, request.FILES)
        if pattern_form.is_valid():
            pattern = pattern_form.save(commit=False)
            pattern.created_by = request.user
            pattern.slug = slugify(pattern.pattern_name)
            pattern.save()
            messages.success(request, 'Your pattern was added successfully!')
            return redirect('patterns')

    else:
        pattern_form = PatternForm()

    return render(
        request,
        "pattern/add_pattern.html",
        {
            'pattern_form': pattern_form
        },
    )


@login_required
def like_pattern(request, slug):
    pattern = get_object_or_404(Pattern, slug=slug)

    if pattern.created_by == request.user:
        messages.add_message(
            request, messages.ERROR, "You can't like your own pattern!")
    else:

        if pattern.likes.filter(id=request.user.id).exists():
            pattern.likes.remove(request.user)
            messages.add_message(
                request, messages.ERROR,
                "Didn't like the pattern? Well, there are other nice patterns!"
            )
        else:
            pattern.likes.add(request.user)
            messages.add_message(
                request, messages.SUCCESS, 'We too like this pattern!')

    return HttpResponseRedirect(reverse('pattern_details', args=[slug]))


@login_required
def add_to_project_list(request, slug):
    pattern = get_object_or_404(Pattern, slug=slug)
    user = request.user
    project_list, _ = ProjectList.objects.get_or_create(user=user)

    if pattern in project_list.patterns.all():
        messages.error(request, 'Pattern is already in your project list.')
    else:
        project_list.patterns.add(pattern)
        messages.success(request, 'Pattern added to your project list.')

    return HttpResponseRedirect(reverse('pattern_details', args=[slug]))


def my_page(request):
    user = request.user
    pattern_names = get_liked_pattern_names(user)
    my_patterns = get_pattern_created_by(user)
    project_patterns = get_added_to_list(user)
    return render(
        request,
        'pattern/my_page.html',
        {
            'pattern_names': pattern_names,
            'my_patterns': my_patterns,
            'project_patterns': project_patterns
        })


def get_liked_pattern_names(user):
    liked_patterns = Pattern.objects.filter(likes=user)
    pattern_names_and_slugs = [
        (
            pattern.pattern_name,
            pattern.slug
        ) for pattern in liked_patterns
    ]
    return pattern_names_and_slugs


def get_pattern_created_by(user):
    my_patterns = Pattern.objects.filter(created_by=user)
    pattern_names_and_slugs = [
        (pattern.pattern_name, pattern.slug) for pattern in my_patterns]
    return pattern_names_and_slugs


def get_added_to_list(user):
    project_list = ProjectList.objects.filter(user=user).first()
    if project_list:
        pattern_names_and_slugs = [
            (
                pattern.pattern_name,
                pattern.slug
            ) for pattern in project_list.patterns.all()
        ]
        return pattern_names_and_slugs
    else:
        return []

pattern/templates/pattern/add_pattern.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<!-- add_pattern.html content starts here -->

<div class="container px-4 py-5">
    <div class="row">
        <div class="col-lg-6">
            <div class="form">
                {% if user.is_authenticated %}
                <h2>Add Pattern</h2>
                <form id="patternForm" method="POST" style="margin-top: 1.3em;" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% crispy pattern_form %}
                </form>
                {% else %}
                <p>You must be logged in to add your pattern</p>
                {% endif %}

                <!-- Display message -->
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- add_pattern.html content ends here -->

{% endblock content %}

pattern/templates/pattern/my_page.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- content starts here -->

<div class="container px-4 py-5 cols-2">
    <div class="mb-3" style="max-width: 540px;">
        <h2>Welcome {{ user.username }} to your page</h2>
        <div class="pattern-list patterns-like">
            <h4>Patterns I like:</h4>
            <ul>
                {% for pattern_name, pattern_slug in pattern_names %}
                <li>
                    <strong><a href="{% url 'pattern_details' slug=pattern_slug %}"
                            class="link-dark">{{ pattern_name }}</a></strong>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="pattern-list patterns-created">
            <h4>Patterns I created:</h4>
            <ul>
                {% for pattern_name, pattern_slug in my_patterns %}
                <li>
                    <strong><a href="{% url 'pattern_details' slug=pattern_slug %}"
                            class="link-dark">{{ pattern_name }}</a></strong>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="pattern-list patterns-to-knit">
            <h4>What I will knit:</h4>
            {% if project_patterns %}
            <ul>
                {% for pattern_name, slug in project_patterns %}
                <li><strong><a href="{% url 'pattern_details' slug=slug %}"
                            class="link-dark">{{ pattern_name }}</a></strong></li>
                {% endfor %}
            </ul>
            {% else %}
            <p>No patterns in your project list yet.</p>
            {% endif %}
        </div>
    </div>
</div>


<!-- content ends here -->

{% endblock content %}

pattern/templates/pattern/pattern_details.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<!-- pattern_details.html content starts here -->
<div class="container px-4 py-5 cols-2" style="max-width: 800px;">
    <div class="row g-0">
        <div class="card text-center">
            <div class="card-header">
                <div>
                    <img src="{{ pattern.featured_image.url }}" alt="{{ pattern.pattern_name }}"
                        class="img-fluid rounded-start" style="width: 100%;">
                </div>
            </div>
            <div class="card-body">
                <h5 class="card-title">{{pattern.pattern_name}} | <small class="text-body-secondary">by
                        {{pattern.created_by}}</h5>
                <div class="row">
                    <div class="liking_pattern col px-4 mb-4 mt-3">
                        {% if user.is_authenticated %}
                        {% if request.user in pattern.likes.all %}
                        <a href="{% url 'like_pattern' slug=pattern.slug %}">Unlike</a>
                        {% else %}
                        <a href="{% url 'like_pattern' slug=pattern.slug %}">Like</a>
                        {% endif %}
                        {% endif %}
                        <div><i class="fa-solid fa-thumbs-up"></i> {{ pattern.likes.count }}</div>
                    </div>
                </div>
                <p class="alert alert-info" role="alert"><em>Difficulty level:</em>
                    {{ pattern.get_difficulty_level_display }}
                    <br><em>Needle size:</em> {{pattern.needle_size}}
                    <br><em>Yarn:</em> {{pattern.yarn}}
                    <br><em>Gauge:</em> {{pattern.gauge}}
                </p>
                <p class="card-text text-start">{{pattern.description}}</p>
                <div class="row">
                    <div class="add_to_project_list col px-4 mb-4 mt-3">
                        {% if user.is_authenticated %}
                        {% if pattern in user.projectlist.patterns.all %}
                        <p>Already in your project list</p>
                        {% else %}
                        <form action="{% url 'add_to_project_list' slug=pattern.slug %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-info">Add to Project List</button>
                        </form>
                        {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Creating New Comments -->
    <div class="col mb-4 mt-3">
        <div>
            {% if user.is_authenticated %}
            <h5>Leave a comment:</h5>
            <p>Posting as: {{ user.username }}</p>
            <form id="commentForm" method="post" style="margin-top: 1.3em;">
                {{ comment_form | crispy }}
                {% csrf_token %}
                <button id="submitButton" type="submit" class="btn btn-success btn-sm">Submit</button>
            </form>
            {% else %}
            <p>Log in to leave a comment</p>
            {% endif %}
        </div>
    </div>

    <!-- Displaying Comments -->
    <div class="row">
        <div class="col-md-8 mb-4  mt-3 ">
            <h5>Comments:</h5>
            <div>
                {% for comment in comments %}
                <div class="p-2 comments">
                    <p class="font-weight-bold">
                        {{ comment.author }} |
                        <span class="font-weight-normal">
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    <div id="comment{{ comment.id }}">
                        {{ comment.body | linebreaks }}
                        <p>---------------------------</p>
                    </div>
                    {% if user.is_authenticated and comment.author == user %}
                    <button class="btn btn-secondary btn-sm btn-edit" comment_id="{{ comment.id }}">Edit</button>
                    <button class="btn  btn-danger btn-sm btn-delete" comment_id="{{ comment.id }}">Delete</button>
                    {% endif %}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
    </div>
</div>
</div>



<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete comment?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete your comment? This action cannot be undone.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a id="deleteConfirm" href="#" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

pattern/templates/pattern/patterns.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Content starts here -->
<style>
    .darkened-img {
        background-image: linear-gradient(rgba(10, 78, 96, 0.5), rgba(0, 0, 0, 0.5));
    }
</style>

<div class="container px-4 py-5" id="custom-cards">
    <h2 class="pb-2 border-bottom">Patterns</h2>
    <a href="{% url 'add_pattern' %}" class="btn btn-primary">Add Pattern</a>
    <div class="row g-4 py-5">
        <!-- Pattern cards -->
        {% for pattern in object_list %}
        <div class="col mb-4">
            <div class="card card-cover overflow-hidden text-bg-dark rounded-4 shadow-lg"
                style="background-image: url('{{ pattern.featured_image.url }}'); background-size: cover; background-position: center; margin-bottom: 20px;">
                <div class="d-flex flex-column p-5 pb-3 text-white darkened-img">
                    <div class="d-flex"><i class="fa-solid fa-thumbs-up"></i>{{ pattern.like_count }}</div>
                    <h3 class="pt-5 mt-5 display-7 lh-1 fw-bold">{{ pattern.pattern_name }}</h3>
                    <h4 class="mb-4">by {{ pattern.created_by }}</h4>

                    <ul class="d-flex list-unstyled mt-auto">
                        <li class="d-flex align-items-center me-3">
                            <small><strong>Difficulty level:
                                    <br>
                                </strong> {{ pattern.get_difficulty_level_display }}</small>
                        </li>
                        <li class="d-flex align-items-center me-3">
                            <small><strong>Gauge:
                                    <br>
                                </strong> {{ pattern.gauge }}</small>
                        </li>
                        <li class="d-flex align-items-center me-3">
                            <small><strong>Needle size:
                                    <br>
                                </strong> {{ pattern.needle_size }}</small>
                        </li>
                    </ul>
                    <ul class="d-flex list-unstyled mt-auto">
                        <li class="d-flex align-items-center">
                            {% if pattern.slug %}
                            <small><a href="{% url 'pattern_details' slug=pattern.slug %}" class="link-info">View
                                    pattern</a></small>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<!-- Content ends here -->
{% endblock %}